### ISSUE TITLE
New Groundlayouts Minors - DFS Style

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#127]
Mit dem Tool aus München neues Groundlayout im DFS Stil für EDLW, EDLP, EDLV, EDFH, EDLN, EDDR, EDSB, EDFH. 

Für EDDG und EDFM gibt es leider keine Daten.

**Comment by LeoKle** [comment]
closing this issue, continuing in #186 as this requires a bit more side work
