### ISSUE TITLE
ATIS "radar vectors"

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#143]
Prüfen wo "expect radar vectors" noch mit in die ATIS muss/sollte.

**Comment by capzDE** [comment]
In Düsseldorf steht "EXPECT VECTORS ILS APPROACH" drin, ausgesprochen genauso.
Wenn beide Pisten in Betrieb sind, steht "EXPECT VECTORS ILS APPROACH RWY 23 RIGHT" bzw. je nach Piste drin. Danach steht dann weiterhin "RWY 23L 23R", ausgesprochen wie gehabt "runways in use 23L and 23R".

**Comment by capzDE** [comment]
> Leider komme ich persönlich nicht mehr auf https://atis.report/ , vielleicht runtergenommen.

Gleiches bei https://acars.adsbexchange.com/. Vermute da mag es irgendwer nicht, dass diese Downlinks da public gestellt werden.
Ich hab noch Screenshots von der ADSB-exchange Seite, da stand in EDDK nichts von Vectors (besagtes CDO Thema wird dort "EXPECT CDO FOR ILS APCH RWY32R OR RNP APCH RWY32L" in dem Beispiel hier geschrieben), in EDDL wie oben beschrieben, in EDDS steht konkret "EXPECT VECTORING FOR ILS APPROACH", und in EDDF steht in der ARR-ATIS _nach_ den Runways in use "EXPECT RADAR VECTORING, GLS APCH ON REQUEST". Für EDDG und EDDR konnte ich damals leider nichts finden, aber ich kann mal ganz unschuldig bei 'ner RW Pilotin nachfragen, ob sie da zufällig schauen könnte, was bei den beiden Plätzen drinsteht.
Alle anderen Plätze in Langen haben lediglich eine Voice-ATIS, da müsste man also entweder anrufen wo möglich oder Piloten die in der Gegend fliegen bitten, doch mal reinzuhören und Bescheid zu geben.

> Bei den AFIS ist klar das es dort nur Runway in use gibt und nicht den Approach.

Interessant, steht dann nicht für die IFRler auch noch dabei, ob sie ILS, RNP, etc. expecten können, zumindest wenn es mehrere gibt? 🤔

**Comment by capzDE** [comment]
Hab eben mal ein paar (alle wo es meines Wissens in EDGG noch geht) über Telefon abhörbare ATISe angerufen:

EDTY hat "expect radar vectors for RNP approach runway 10".
EDGS hat leider irgendwie nicht geklappt, da kam nur ewig Freizeichen.
EDLA hat keine IFR Verfahren, aber trotzdem mal reingehört: reine Wetterinfo, aktive Piste wird hier nicht genannt.

**Comment by Phil061995** [comment]
Vatsim Airports aktuell ohne "expect vectors":
- [ ] EDDG | ILS/LOC, RNAV, NDB
- [ ] EDDK | ILS/LOC, RNP - raus wenn &cdo
- [ ] EDDR | ILS/LOC, RNP, VOR, NDB
- [ ] EDDS | ILS/LOC, RNP, VOR - raus wenn &cdo + &cdo hinzufügen
- [ ] EDFH | ILS/LOC, RNP, NDB
- [ ] EDFM | LOC, RNAV
- [ ] EDLN | ILS/LOC, RNP, VOR
- [ ] EDLP | ILS/LOC, RNP, NDB
- [ ] EDLV | ILS/LOC, RNP, NDB
- [ ] EDLW | ILS/LOC, RNP, VOR
- [ ] EDSB | ILS/LOC, RNP, NDB

.. "EXPECT VECTORING FOR ILS APPROACH" ..

.. "EXPECT CDO FOR ILS APPROACH" .. (DK, DS)

Ich würde sagen wir machen das auf Vatsim für alle Flughäfen bei uns gleich, da uns auch einfach verlässliche, aktuelle reale Quellen fehlen.

@K0nnyy magst du das dann zusammen mit dem Handoff anpassen?

**Comment by capzDE** [comment]
> EDFM | LOC, RNAV

Hier am besten auch nochmal nach dem Circling schauen, das scheint wohl nicht zu funktionieren wie es soll, cf. #232 

> Vatsim Airports aktuell ohne "expect vectors":

In der Liste fehlen die RMZ und MIL Plätze mit ATIS, das wären:
- EDFQ | RNAV (29)/RNAV+circling (11)
- EDGS | ILS/LOC/RNP
- EDLA | none, weather info only
- (EDRY | RNP, published aber NOTAM U/S bis AFIS und IFR Verfahren tatsächlich verfügbar sind, dementsprechend noch nicht implementiert)
- EDTY | ILS/RNP
- ETAD | ILS/RNP/TACAN
- ETAR | ILS/RNP/TACAN
- ETNG | ILS/RNAV/TACAN, hier wird eigentlich 09 departure und 27 arrival gefahren, evt. kann man das irgendwie einbauen?
- ETOU | ILS/RNAV/TACAN

**Comment by K0nnyy** [comment]
ATIS komplett überarbeitet, "EXPECT VECTORING FOR ..." ist jetzt standard in allen Langen Plätzen.

Die von dir genannten Airports @capzDE haben alle kein Profil auf Uniatis. Es wäre sehr aufwendig diese alle anzulegen, ist das tatsächlich nötig?

**Comment by Phil061995** [comment]
@capzDE Profil für die kleinen Info Plätze in meinen aktuell nicht notwendig, wenn dann bitte neues Issue oder die Möglichkeiten mit vATIS ausloten. :)
