### ISSUE TITLE
ECLs im Bereich PFA verlängern

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#145]
Beitrag im Thema '[BUGREPORTS] Euroscope-Package and Featurerequests' https://board.vatsim-germany.org/threads/bugreports-euroscope-package-and-featurerequests.69153/post-964736

**Comment by capzDE** [comment]
Generell müssten wir da mal schauen, mir fällt das auch auf dem HMM, auf dem STG, und selbst auf DFAN mit den sekundären Plätzen immer wieder auf wenn da Verkehr ist den man draufvektoriert: die Centerlines sind ultrakurz und teilweise werden nichtmal IAFs/IFs/FAFs eingeblendet.
Evt. kann man da mal bis 2404 oder 2405 generell drübergehen und schauen wo man nachbessern könnte.

**Comment by Phil061995** [comment]
Ich hab jetzt bei HMM mal geschaut, für EDDG, EDLW und EDLP reicht die ECL jeweils 4-5 NM über den FAF raus. Brauchen wir da wirklich noch so viel mehr?

**Comment by capzDE** [comment]
Centerlines sollten mit 2412 Anpassungen alle passen.
