### ISSUE TITLE
Topsky Map AoR ETNN

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#149]
Beitrag im Thema '[BUGREPORTS] Euroscope-Package and Featurerequests' https://board.vatsim-germany.org/threads/bugreports-euroscope-package-and-featurerequests.69153/post-965531

**Comment by capzDE** [comment]
Teil von MIL Update #24 - geplant ist für ETNN, nur Sektoren B und C auf VATSIM zu verwenden.
