### ISSUE TITLE
EDUU Bilder gehen nicht

### ISSUE THREAD

**Issue by LeoKle** [VATGER-Nav/edgg-package#155]
https://knowledgebase.vatsim-germany.org/books/eduu-rhein-radar/page/sector-splits-eduu-above-edgg

**Comment by K0nnyy** [comment]
https://dms.vatsim-germany.org/apps/files/?dir=/EDGG/Sectormaps/Rhein%20Splits%202302%20Test&fileid=80490

**Comment by LeoKle** [comment]
Ich habe die Bilder aus dem verlinkten Ordner hierhin verschoben, dass erlaubt uns später die Bilder einfacher zu ersetzen:
https://github.com/VATGER-Nav/sector-maps/tree/main/custom/eduu
