### ISSUE TITLE
LoA Änderungswünsche EDGG

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#171]
Anfrage von Bennet Barz: Wie bereits mit Leon besprochen 1-2 Ergänzungen und/oder fragen zu unseren LOA‘s und ob diese in unsere LOA‘s ergänzt werden könnten.

**Langen internal:**
- [x] PADH: DCT DOMUX north of PADBA
- [x] PADH darf direct KOPAG und zudem on request by DKA, after KOPAG direct WYP/COL (je nach Betriebsrichtung) (teilweise bei 32 Betrieb auch DCT COL - das ist aber Tagesabsprache) - ähnlich wie das DK416/WYP Agreement mit GIN
- [x] BOT darf DCT MEVEL (scheinbar gibt es da real auch nichts - so habe ich es zumindest verstanden - und sie machen es einfach, da evtl. nochmal nachfragen)
- [x] typo: RID VOR noch vorhanden auf Seite 12 unter Note 3
- [x] typo: note 2 unter 1.1.6 sind RWY 13 und 31 vertauscht
- [x] 2408 sector changes: AWY Z74 skippt KNG, und geht direkt HAB->DKB

**EDGG/YY - EHAA:**
- [x] da sowieso fast alle EDYY exits rlsd sind, könnte man da evtl einfach mal fragen, ob man hier auch einfach EDYY exit von EHAA clearen darf und sie unsere, statt so viele Wegpunkte aufzuschreiben
- [x] DCT NORKU/RKN bei FL240- / wir machen das auf VATSIM sowieso eigentlich immer - evtl. mit aufnehmen, weil diese Punkte schon leicht im EHAA liegen

**EDYY internal:**
- [ ] EHAA - FIR Langen LOA haben andere/mehr directs rlsd. als in internal vorhanden
- [ ] ~~Evtl. EBBU fragen, ob diese auch EDYY exits freigeben? (RAPOR, FAMEN etc)~~
- [ ] EKDK - EDWW directs: Darf das nur JEV/HOL oder EDYY komplett? Wenn komplett (so würde ich mal vermuten ist es real) evtl. in internal aufnehmen - habe hier als Trainee mehrere Meinungen schon bekommen (von darf ich geben, über im CPT sollte ich es nicht tun, bis zu auf keinen Fall machen)

**EDYY - EDUU LOA/EDYY internal:**
- [x] sollen hier die RHR directs immer frei von NTM bleiben? BOMBI hat diese condition, NEGIX, TESGA etc haben es nicht. Heißt, wenn NTM/FFM combined, darf ich mit NEGIX z.B. durch den NTM, bei BOMBI nicht. Hier evtl. verallgemeinern?

**Comment by Phil061995** [comment]
@LeoKle @K0nnyy habt ihr was das dagegen spricht? Ansonsten würden die Punkte in die anstehenden LoA Anpassungen mit aufgenommen bzw. geklärt werden.

**Comment by capzDE** [comment]
In der EDGG internal, Seite 9, Note 2 ist runway 13 und 31 vertauscht, das müssen wir beizeiten mal korrigieren.

**Comment by capzDE** [comment]
Und mit den geänderten Sektoren von 2408 hat sich internally ein bisschen was geändert: AWY Z74 Flüge skippen den HAB und gehen direkt von KNG and DKB.

**Comment by capzDE** [comment]
EBBU gibt vorerst keine weiteren Exits frei. Überlegung unsererseits relevante EB-Rs zu hinterlegen und auf AUP-Basis automatisch zu aktivieren, da Grund seitens EBBU ebendieser militärische Luftraum ist - unsere Lotsen müssten dann beim Vergeben von Directs die Aktivität von diesen Lufträumen berücksichtigen.

**Comment by Phil061995** [comment]
@capzDE den Vorschlag halte ich nicht sinnvoll für umsetzbar. Dann lieber einfach den direct koordinieren.

**Comment by capzDE** [comment]
> den Vorschlag halte ich nicht sinnvoll für umsetzbar. Dann lieber einfach den direct koordinieren.

Naja, es sind für EDYY vier areas, fünf wenn man die um den Königspalast mitzählt. Denke, dass man das durchaus irgendwie einfädeln könnte, dass BeLux uns da die Definitionen aus ihrem Package geben und uns dann jeweils die neuen Definitionen schicken sollen wenn sich was ändert. Selbst wenn man im Lower noch die 2-3 für Köln und Düsseldorf LoA-relevanten areas mitnimmt dürfte das denke ich kein allzu großes Problem sein und da es das ja letzten Endes einfacher macht und wir dann unter Beachtung der areas einfach alles clearen dürften 🤷‍♀️

-------------------

Verbleibende EDYY Punkte schauen wir uns down the road mal an, aktuell erste Schritte in Richtung möglicher gemeinsamer EDYY LoAs mit Dutch und BeLux, die Umsetzung von solchen Sachen weitaus einfacher machen würden.

**Comment by capzDE** [comment]
Everything further in #255
