### ISSUE TITLE
EHAA, EDYY, EDWW CPDLC Codes 

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#181]
Aktuell fehlen die EHAA CPDLC Codes im Topsky File.

**Comment by capzDE** [comment]
Zusätzlich fehlt wohl EDYY Delta und EDWW Eider West ist mit falschem Logon hinterlegt, siehe https://board.vatsim-germany.org/threads/bugreports-euroscope-package-and-featurerequests.69153/post-972875.
