### ISSUE TITLE
missing and superfluous sector borders

### ISSUE THREAD

**Issue by capzDE** [VATGER-Nav/edgg-package#182]
reported in the forum:

sector borders NOR/DKA always shown, even when only NOR is staffed, border can't be turned off via TS maps
sector borders to OLN/NTM in DEVRU area missing
sector borders DLA/DLD not shown despite active split, border can't be turned on via TS maps

**Comment by Phil061995** [comment]
![grafik](https://github.com/VATGER-Nav/edgg-package/assets/67208671/79a6baa6-3c6a-401a-b64e-7bf81d59e7da)
Vorschlag mit eigener NOR APP AoR, Grenze zwischen NOR und DKA kann über TS Maps eingeblendet werden.
