### ISSUE TITLE
EBBU LoA Update

### ISSUE THREAD

**Issue by LeoKle** [VATGER-Nav/edgg-package#188]
Änderungen für LoA:
EBBR, EB* Departures über ELDAR gehen ab AIRAC 06 FL250 an den RHR
Staffelungsverpflichtung verbleibt unverändert, Sind rlsd for Turn by NOR und Profil muss clear of OLNO sector sein

Zu 2406 wird es nichts mehr. Ich würde es einbauen, wenn wir vielleicht noch ein paar Sachen mehr zum Ändern haben.

**Comment by capzDE** [comment]
already included in EDGG-EDYY LoA
