### ISSUE TITLE
Überarbeitung EDDL

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#19]
Pilotenbriefing für EDDL muss entsprechend der Briefings für Langen überarbeitet, übersetzt und für die KB aufbereitet sowie eingefügt werden.

Aktuelle Version noch im Wiki: https://de.wiki.vatsim-germany.org/Flughafen_D%C3%BCsseldorf_Pilotenbriefing

- Entwurf erstellen (englisch)
- Quicklink erstellen: vats.im/eddl

**Comment by capzDE** [comment]
https://vats.im/eddl Briefing live
