### ISSUE TITLE
Airport max. Startup at the same time

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#229]
Diskussionsgrundlage. Werte sollen dann mit in die SOP aufgenommen werden. Gerne Erfahrunsgwerte mit einbringen. EDDM z.B. hat max. 15 pro Bahn.

- **EDDF:** RWY 25 10 - 12 | 18/07 15 (je nach Traffic geht auch mal mehr)
- **EDDK:** 12
- **EDDL:** 13 bei zwei Bahnen in use, 10 bei single runway (Quelle DFS TWR Lotse DUS)
- **EDDS:** RWY 07 8 - 10? | RWY 25 10 - 12
- **Minors:** 6 mit Inbounds, 8 bei wenig Inbounds

**Comment by capzDE** [comment]
> EDDS: RWY 07 8 - 10? | RWY 25 10 - 12

Wenn wir die durchschnittliche Outboundcapacity von 24/h nehmen und davon ausgehen, dass es bei 25 ca. 20 Minuten von Startup bis Takeoff dauert, dann wären es 8 gleichzeitige Startups (wenn wir davon ausgehen, dass die Piloten generell nicht groß trödeln und eher 15 Minuten brauchen, dann sind es 6 gleichzeitige); wenn wir bei 07 von ca. 10 Minuten ausgehen, dann sind es 4 gleichzeitige.
Aber ist halt das Problem mit einer fixen Zahl und der Methode, es an aktiven Startupclearances festzumachen: wenn du nicht so viel Inbound hast, dann kannst du auch mehr machen (mit den max. 40/h bei 0 Inbounds wären es bspw. 13-14 bei 25 und 6-7 bei 07, mit den den min. 8/h beim totalen Inboundrush hingegen 2-3 bei 25 und 1-2 bei 07).
Hatte hier mal auf Basis der realen ACDM Szenarien [das hier](https://knowledgebase.vatsim-germany.org/uploads/images/gallery/2024-08/scaled-1680-/edds-acdm-scenarios.png) entworfen, ist aber natürlich kein "maximale Startups"-Ding, sondern maximale Outbounds, die dann zurückgerechnet werden auf TSATs.

> Minors: 6 mit Inbounds, 8 bei wenig Inbounds

Weiß nicht, ob man das so pauschalisieren kann. In Mannheim säufste damit komplett ab und wirst sehr wahrscheinlich die max. 20 Minuten bis zur further clearance nach der Startupfreigabe nicht für die ganze Sequenz einhalten können, in Baden kannste im Zweifel wahrscheinlich auch 10 oder mehr laufen haben.

**Comment by Phil061995** [comment]
Klar ist pauschalisieren immer etwas schwierig, für Frankfurt sind die Werte allerdings sehr angenehm. Für DUS hab ich vorhin mal etwas beobachtet wie das sich so verhält, da wars mit 12 immer ganz gut, bei 15/16 waren dann doch recht viele gleichzeitig am HP.

Ohne ACDM sind diese Richtwerte deutlich besser als nichts.

**Comment by Phil061995** [comment]
Hinweis in SOP für EDDF, EDDL, EDDK und EDDS im Bereich Delivery. Bei Minors nicht in die SOP aufgenommen.
