### ISSUE TITLE
EDDK: A Stands on TWY L reopened

### ISSUE THREAD

**Issue by pa-ulex** [VATGER-Nav/edgg-package#235]
Taxiway L is not closed anymore. Here is a FR example:

- https://www.flightradar24.com/2024-10-14/21:58/20x/ABR142/378b1619

From Stand A23/24 its max 36m till the end as seen in satellite images.

**Comment by sergej-singer** [comment]
Resolved with [998f5c7](https://github.com/VATGER-Nav/edgg-package/commit/998f5c7b37df8b507e57e8a100aede7500e0e77e)
