### ISSUE TITLE
ATIS Hinweis Handoff Verfahren

### ISSUE THREAD

**Issue by Phil061995** [VATGER-Nav/edgg-package#252]
Der selbstständige Wechsel der Piloten von TWR zu APP ist weiterhin unzureichend und führt immer wieder zu Problem, unnötiger Koordination und Verwirrung. Durch die fehlenden Lido SIDPT Charts haben die Piloten zudem keine Chance das Verfahren zu kennen, wenn sie nicht bewusst dafür in andere Charts schauen. Ich wäre dafür, dass Verfahren für nach dem Abflug für alle Plätze außer FRA in die ATIS mit aufzunehmen. 

... "WHEN AIRBORNE CONTACT 1XX.XXX" ... // ... "WHEN AIRBORNE MONITOR ADVISORY ON 122.800" ...
- [x] EDDS
- [x] EDDG
- [x] EDDR
- [x] EDFH
- [x] EDFM
- [x] EDLN
- [x] EDLP
- [x] EDLV
- [x] EDLW
- [x] EDSB
- [ ] EDTL

... "WHEN PASSING 2000 FT CONTACT 1XX.XXX" ... // ... "WHEN PASSING 2000 FT MONITOR ADVISORY ON 122.800 " ...
- [x] EDDL
- [x] EDDK

**Comment by K0nnyy** [comment]
EDTL Atis existiert nicht im Setup, Rest ist umgesetzt.
