### ISSUE TITLE
EDDS Update + Kleinkram

### ISSUE THREAD

**Issue by LeoKle** [VATGER-Nav/edgg-package#7]
- [x] Stand assignments
- [ ] RRS Marker Größe
- [x] DFS ASR Feinjustierung der Farben
- [ ] DFS ASR Runway Numbers
- [ ] Angleichung der Tower ASR an die reale Darstellung
- [x] SVFR Squawk 6105 für die Mode A Korrelation (?)
- [x] DFS ASR standardmäßige Einblendung intermediate holdshorts bei Z zwischen R und O
- [x] restrictions maps anpassen zu neuer Betriebsabsprache für code F Flieger im Norden
- [x] GWI callsign zu Gruppe für 10er/40er stands hinzufügen (Inlandsflüge EWG)

**Comment by capzDE** [comment]
Ich schließe das hier mal. Verbleibendes kann im Rahmen von #204 erledigt werden.
