### ISSUE TITLE
LoA Viewer - Check current agreements

### ISSUE THREAD

**Issue by LeoKle** [VATGER-Nav/edgg-package#99]
Check all current agreements

- [x] Langen internal
- [ ] Karlsruhe internal
- [ ] Maastricht internal
- [ ] EDGG - EDWW
- [ ] EDGG - EDMM
- [ ] EDGG - EDUU
- [ ] EDYY - EDUU
- [ ] EDYY - EDGG
- [ ] EDYY - EDWW
- [ ] LSAS - EDGG
- [ ] EHAA - EDGG
- [ ] EBBU - EDGG

**Comment by opoos-code** [comment]
Langen internal checked

**Comment by Phil061995** [comment]
@LeoKle wenn ich das richtig sehe, sind die LoAs jetzt in Github hinterlegt, also bräuchten wir die Überprüfung hier nicht mehr? Oder stammen die Daten aus dem LoA Viewer und müssen noch einmal überprüft werden?

**Comment by LeoKle** [comment]
Prüfen müssten wir sie dennoch, Robin war schon so nett und hat sie ins Repo migriert

**Comment by LeoKle** [comment]
Ich schließe das Issue hier und führe es in #194 fort.
